version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: video
      POSTGRES_USER: videoproject
      POSTGRES_PASSWORD: video
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: ["gunicorn", "assignment.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    name: assignment_default
